version: "3.3"

services:
  node:
    image: node
    container_name: node
    volumes:
      - ./server:/home/app
    working_dir: /home/app
    ports:
      - 80:5000
    command: npm run start
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./db:/data/db